### PR TITLE
Add support for pipenv

### PR DESCRIPTION
**Pull request by Hourann**
The old setup method is still valid. I haven't update [develop.rst](docs/develop.rst) for pipenv because of my poor English. Please update that to pipenv.
Contributors can setup dev environment by change directory into this repo and
```bash
# install dependences for development   
pipenv install --dev 
# active virtual environment
pipenv shell
# deactive virtual environment
deactivate
```

### CODE REVIEW

**Comment by zzl0** [comment]
Thanks for contributing to athenacli.

You English is very good, I can understand everything. Would like to try to update [develop.rst](https://github.com/dbcli/athenacli/blob/master/docs/develop.rst) and delete `requirements-dev.txt`?

**Comment by Hourann** [comment]
Thank you for trusting my poor English. To be honest I have to thank Google Translate😅. If there are any problems with my expression, please correct me. Seems like I have to update `.travis.yml` for deleting `requirements-dev.txt`

**Comment by zzl0** [comment]
Thanks, LGTM. I will merge this and try to solve the lockfile issue.

**Comment by zzl0** [comment]
https://github.com/dbcli/athenacli/issues/24

**Pull request merged**
